version: "3"
services:
  bot_service:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongodb
    volumes:
      - convbot:/app/conversationbot
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret_password
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
  convbot:
